"""initial_schema

Revision ID: 4c13d9b55098
Revises: 
Create Date: 2026-01-25 16:02:19.604300

"""



# revision identifiers, used by Alembic.
revision = '4c13d9b55098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
