"""initial_schema

Revision ID: 3fd4718662e2
Revises: 
Create Date: 2026-01-25 15:52:47.026641

"""



# revision identifiers, used by Alembic.
revision = '3fd4718662e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
