"""initial_schema

Revision ID: 2ee4c06556cd
Revises: 5ebacf275ef4
Create Date: 2026-01-25 15:55:16.146856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee4c06556cd'
down_revision = '5ebacf275ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
