"""initial_migration

Revision ID: 725de98582c4
Revises: 
Create Date: 2026-01-25 15:23:30.005478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725de98582c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
