"""initial_schema

Revision ID: 025a9c4c4f02
Revises: 
Create Date: 2026-01-25 15:40:29.530142

"""



# revision identifiers, used by Alembic.
revision = '025a9c4c4f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
