#!/bin/bash
SERVICE_NAME=$1

if [ -z "$SERVICE_NAME" ]; then
    echo "Usage: $0 <service-name>"
    exit 1
fi

echo "Generating migration for $SERVICE_NAME..."

# 1. Get Pod
POD=$(kubectl get pod -n santhe -l app.kubernetes.io/name=$SERVICE_NAME -o jsonpath='{.items[0].metadata.name}')
if [ -z "$POD" ]; then
    echo "Pod for $SERVICE_NAME not found"
    exit 1
fi

echo "Using pod: $POD"

# 2. Drop Tables (Clean slate for initial migration)
echo "Dropping tables..."
kubectl exec -n santhe $POD -- python3 -c "from src.database import Base, engine; Base.metadata.drop_all(bind=engine)"

# 3. Generate Migration
echo "Generating autogenerated revision..."
kubectl exec -n santhe $POD -- alembic revision --autogenerate -m "initial_schema"

# 4. Apply Migration (Verify it works)
echo "Applying migration..."
kubectl exec -n santhe $POD -- alembic upgrade head

# 5. Copy Migration File to Local
# Find the filename
MIGRATION_FILE=$(kubectl exec -n santhe $POD -- ls migrations/versions | grep .py | head -n 1)
if [ -z "$MIGRATION_FILE" ]; then
    echo "Migration file not found in pod"
    exit 1
fi

echo "Copying $MIGRATION_FILE..."
kubectl cp santhe/$POD:/app/migrations/versions/$MIGRATION_FILE services/$SERVICE_NAME/migrations/versions/$MIGRATION_FILE

echo "Done for $SERVICE_NAME"
